# Generated by Django 5.1.1 on 2024-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_remove_order_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
