# Generated by Django 5.1.1 on 2024-09-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_placeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='cart_items',
            field=models.ManyToManyField(related_name='orders', to='cart.cartitem'),
        ),
    ]
